"""
Render per-color icon variants.
AI-generated by Claude Opus 4.7

Source icons are assumed to be monochrome PNGs with their silhouette
encoded entirely in the alpha channel.

Outputs go to dist/discord_assets/<app>/<prefix>_c###.png. A
upload_manifest.csv is written next to each app's icons listing
(asset_key, color_name, hex).

Run after select_palette.py:
    python colors/render_icons.py
"""
from __future__ import annotations
import csv
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import numpy as np
    from PIL import Image
except ImportError as e:
    sys.exit(
        f"[render] missing dependency: {e}.\n"
        f"        Install with: python -m pip install numpy pillow"
    )

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
PALETTE_CSV = REPO / "colors" / "palette.csv"
OUT_ROOT = REPO / "dist" / "discord_assets"


@dataclass(frozen=True)
class TintTarget:
    """One icon to tint across (some subset of) the palette."""
    app: str                # output subdirectory
    source: Path            # source PNG (monochrome + alpha)
    key_prefix: str         # Discord asset-key prefix
    # If None, render every palette entry. Otherwise render only entries whose
    # `index` matches one of these. Used to give Painter's Paint and Physical
    # Paint distinct icon sets out of the same 250-color palette while staying
    # within Discord's 300 assets-per-app budget.
    index_filter: tuple[int, ...] | None = None


TARGETS = [
    # Painter: split 125/125 between Paint and Physical Paint. Alternating
    # indices on the L-sorted palette gives each brush balanced coverage of
    # the full lightness range. Total Painter uploads: 250 (matches others).
    TintTarget(
        app="painter",
        source=REPO / "icons" / "substance_painter" / "Paint.png",
        key_prefix="paint",
        index_filter=tuple(range(0, 250, 2)),    # even -> 125 entries
    ),
    TintTarget(
        app="painter",
        source=REPO / "icons" / "substance_painter" / "Physical paint.png",
        key_prefix="pphys",
        index_filter=tuple(range(1, 250, 2)),    # odd -> 125 entries
    ),
    # Krita: Freehand Brush gets the full palette. Other brush-family tools
    # keep their normal monochrome icon; hover text still gets the color name.
    TintTarget(
        app="krita",
        source=REPO / "icons" / "krita" / "KritaShape_KisToolBrush.png",
        key_prefix="kbrush",
        index_filter=None,                       # all 250
    ),
    TintTarget(
        app="gimp",
        source = REPO / "icons" / "gimp" / "paintbrush.png",
        key_prefix="paintbrush",
        index_filter=None
    )
]


# Discord asset key constraints we want to enforce as we generate.
_MAX_KEY_LEN = 32


def _hex_to_rgb(hex_str: str) -> tuple[int, int, int]:
    h = hex_str.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def _load_palette() -> list[dict]:
    with PALETTE_CSV.open("r", encoding="utf-8", newline="") as fp:
        return list(csv.DictReader(fp))


def _tint(source_arr: "np.ndarray", rgb: tuple[int, int, int]) -> "np.ndarray":
    """Return a new RGBA array with RGB set to `rgb` and alpha preserved.

    Source is assumed RGBA uint8. We overwrite the three color channels
    wholesale — the per-pixel RGB variation in the source (std ~1.5) is
    anti-aliasing artifact that doesn't carry shape and isn't worth keeping
    once we recolor.
    """
    out = source_arr.copy()
    out[..., 0] = rgb[0]
    out[..., 1] = rgb[1]
    out[..., 2] = rgb[2]
    return out


def render_target(target: TintTarget, palette: list[dict]) -> tuple[Path, int, int]:
    """Render the configured subset of palette entries for one TintTarget.

    Returns (out_dir, num_rendered, longest_key_len). Per-target manifests are
    appended to (rather than overwritten on) the per-app upload_manifest.csv,
    so multiple targets writing to the same app share one manifest.
    """
    if not target.source.exists():
        raise FileNotFoundError(f"source icon not found: {target.source}")

    out_dir = OUT_ROOT / target.app
    out_dir.mkdir(parents=True, exist_ok=True)

    # Load the source once.
    src_img = Image.open(target.source).convert("RGBA")
    src_arr = np.array(src_img, dtype=np.uint8)

    index_filter = (
        None if target.index_filter is None else frozenset(target.index_filter)
    )

    manifest_rows: list[tuple[str, str, str, str]] = []
    longest_key = 0

    for row in palette:
        if index_filter is not None and int(row["index"]) not in index_filter:
            continue
        suffix = row["key_suffix"]
        key = f"{target.key_prefix}_{suffix}"
        longest_key = max(longest_key, len(key))
        if len(key) > _MAX_KEY_LEN:
            raise ValueError(
                f"asset key '{key}' is {len(key)} chars, exceeds Discord's "
                f"{_MAX_KEY_LEN}-char limit"
            )
        rgb = _hex_to_rgb(row["hex"])
        out_arr = _tint(src_arr, rgb)
        Image.fromarray(out_arr, mode="RGBA").save(
            out_dir / f"{key}.png", format="PNG", optimize=True
        )
        # display_name is the augmented name when present; fall back to name
        # for compatibility with older palette.csv revisions.
        display = row.get("display_name") or row["name"]
        manifest_rows.append((key, display, row["name"], row["hex"]))

    # Append-or-create the per-app upload manifest. When multiple targets share
    # an app (Painter: Paint + Physical Paint), all rows accumulate in one file.
    manifest = out_dir / "upload_manifest.csv"
    write_header = not manifest.exists()
    with manifest.open("a", encoding="utf-8", newline="") as fp:
        writer = csv.writer(fp)
        if write_header:
            writer.writerow(["asset_key", "display_name", "raw_name", "hex"])
        writer.writerows(manifest_rows)

    return out_dir, len(manifest_rows), longest_key


def main() -> None:
    if not PALETTE_CSV.exists():
        sys.exit(
            f"[render] palette.csv not found at {PALETTE_CSV}.\n"
            f"        Run colors/select_palette.py first."
        )
    palette = _load_palette()
    print(f"[render] palette: {len(palette)} entries")

    # Wipe prior output so a stale Paint.png from the old 250-shared scheme
    # doesn't linger alongside the new 125-split files.
    if OUT_ROOT.exists():
        import shutil
        shutil.rmtree(OUT_ROOT)
    OUT_ROOT.mkdir(parents=True, exist_ok=True)

    for target in TARGETS:
        if not target.source.exists():
            print(f"[render] SKIP {target.app}/{target.key_prefix}: missing {target.source}")
            continue
        out_dir, n, longest = render_target(target, palette)
        print(f"[render] {target.app:8s} {target.key_prefix:7s}: {n:3d} icons -> "
              f"{out_dir.relative_to(REPO)}  (longest key {longest}/{_MAX_KEY_LEN})")

    print(f"[render] done -> {OUT_ROOT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
