"""
Build a 250-entry color palette from colornames.bestof.csv.
AI-generated by Claude Opus 4.7

Strategy:
  1. Load every named color and convert to OKLab via standard sRGB linearization
     + Björn Ottosson's OKLab matrix.
  2. Filter to "evocative" names: drop entries that are bare modifier+primary
     phrases ("Light Blue"), contain digits, or are common boring patterns.
     We want names that are informative AND interesting.
  3. Farthest-point sampling on the filtered names in OKLab to pick 250 that
     are well-spread perceptually. This guarantees every chosen entry is both
     a real named color AND from the evocative pool, with no awkward back-
     matching step.
  4. For each chosen entry, compute a `display_name`: if the name already
     conveys a color (contains words like "blue", "tomato", "violet" — even
     as a substring, so "Extraviolet" counts), keep as-is; otherwise append
     a primary color derived from OKLab hue/lightness/chroma. This is what
     turns ambiguous names like "Sea Serpent's Tears" into "Sea Serpent's
     Tears Blue" so the user can interpret the name without a color swatch.
  5. Write palette.csv with index, key_suffix (cNNN), name, display_name,
     hex, OKLab L/a/b.

Run once; output is committed.
"""
from __future__ import annotations
import csv
import math
import re
from pathlib import Path
from typing import Iterable, NamedTuple

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
INPUT_CSV = HERE / "colornames.bestof.csv"
# The canonical palette lives in the colors/ package so plugins can `from colors
# import find_closest`. The one-shot here writes through to it.
OUTPUT_CSV = REPO / "colors" / "palette.csv"
PALETTE_SIZE = 250


# ----------------------------------------------------------------------------
# sRGB -> OKLab
# ----------------------------------------------------------------------------

def _srgb_decode(c: float) -> float:
    """Undo sRGB gamma. Input in [0, 1], output linear-light in [0, 1]."""
    if c <= 0.04045:
        return c / 12.92
    return ((c + 0.055) / 1.055) ** 2.4


def hex_to_linear_srgb(hex_str: str) -> tuple[float, float, float]:
    h = hex_str.lstrip("#")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return _srgb_decode(r), _srgb_decode(g), _srgb_decode(b)


def linear_srgb_to_oklab(r: float, g: float, b: float) -> tuple[float, float, float]:
    """Björn Ottosson's OKLab transform: linear sRGB -> OKLab."""
    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b

    l_ = l ** (1.0 / 3.0) if l >= 0 else -((-l) ** (1.0 / 3.0))
    m_ = m ** (1.0 / 3.0) if m >= 0 else -((-m) ** (1.0 / 3.0))
    s_ = s ** (1.0 / 3.0) if s >= 0 else -((-s) ** (1.0 / 3.0))

    return (
        0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
        1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
        0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
    )


def hex_to_oklab(hex_str: str) -> tuple[float, float, float]:
    return linear_srgb_to_oklab(*hex_to_linear_srgb(hex_str))


# ----------------------------------------------------------------------------
# Evocative-name filter
# ----------------------------------------------------------------------------

# Pure modifier + base color: "Light Blue", "Very Dark Red", "Pale Pink",
# "Medium Soft Brown". Matches *only* such patterns; "Light of Dawn" or
# "Pale Horseman" survive because there's an interesting noun.
_BORING_MODIFIERS = (
    "very", "light", "lite", "dark", "darker", "darkish", "lighter",
    "bright", "brighter", "brightish", "pale", "paler", "deep", "deeper",
    "soft", "softer", "warm", "warmer", "cool", "cooler", "medium", "mid",
    "neutral", "pure", "standard", "classic", "true", "plain", "basic",
    "muted", "vivid", "vibrant", "rich", "dull", "dusty", "dusky",
    "faded", "subtle", "intense", "ultra", "super", "extra",
    "regular", "normal", "ordinary", "generic",
)
_PRIMARY_COLORS = (
    "red", "green", "blue", "yellow", "orange", "purple", "pink",
    "brown", "black", "white", "gray", "grey", "cyan", "magenta", "violet",
    "indigo", "teal", "lime", "olive", "maroon", "navy", "tan", "beige",
    "ivory", "khaki", "salmon", "coral", "crimson", "scarlet", "azure",
    "amber", "lavender", "mint", "rose", "rust", "wine", "cream", "peach",
    "fuchsia", "gold", "silver", "bronze", "copper", "lilac", "plum",
    "turquoise", "aqua", "chartreuse", "mauve", "ochre", "sepia",
)

_HEX_HASH_RE = re.compile(r"#[0-9a-f]+", re.IGNORECASE)


def _normalize_words(name: str) -> list[str]:
    # Strip diacritics-cheap (Cafe vs Café both lowercase to the same)? We
    # keep them since they don't affect the regex below; we only inspect
    # ASCII-lowered word tokens for boring/primary classification.
    return re.split(r"[\s\-–—]+", name.lower())


def is_evocative(name: str) -> bool:
    """Return True if the name passes the 'interesting' filter."""
    raw = name.strip()
    if not raw:
        return False

    # Digits anywhere kill evocativeness: "100 Mph", "8 Bit Eggplant", "3am".
    if any(ch.isdigit() for ch in raw):
        return False

    words = [w for w in _normalize_words(raw) if w]
    if not words:
        return False

    # Single-word bare primary: "Red", "Pink".
    if len(words) == 1 and words[0] in _PRIMARY_COLORS:
        return False

    # Pure modifier+primary stack: every word is either a boring modifier or
    # a primary color. "Light Blue", "Dark Bluish Green", "Very Pale Pink".
    # Allow if there's at least one *interesting* word.
    interesting_token = False
    for w in words:
        if w in _BORING_MODIFIERS:
            continue
        if w in _PRIMARY_COLORS:
            continue
        if w in {"ish", "ly", "y"}:  # rare adjective suffixes left dangling
            continue
        interesting_token = True
        break
    if not interesting_token:
        return False

    # Names that look like color-codes ("X-11 Brown"): caught by digit check.
    # Names containing "#hex": pass-through; the digit filter catches them.
    return True


# ----------------------------------------------------------------------------
# Display name: append primary color suffix when name doesn't imply one
# ----------------------------------------------------------------------------

# Substring-matched against the lowercased name. We use substring (not
# whole-word) so compounds like "Extraviolet" / "Bluebird" / "Roseate" still
# count as having an implicit color cue. False positives (name contains the
# substring but isn't actually about that color) only cause us to *not* add
# a suffix — never to add the wrong one — so they're cheap.
_COLOR_HINT_SUBSTRINGS = tuple(sorted({
    # Basic + named colors
    "red", "green", "blue", "yellow", "orange", "purple", "pink", "brown",
    "black", "white", "gray", "grey", "cyan", "magenta", "violet", "indigo",
    "teal", "lime", "olive", "maroon", "navy", "beige", "ivory", "khaki",
    "salmon", "coral", "crimson", "scarlet", "azure", "amber", "lavender",
    "mint", "rose", "rust", "wine", "cream", "peach", "fuchsia",
    "gold", "silver", "bronze", "copper", "lilac", "plum", "turquoise",
    "aqua", "chartreuse", "mauve", "ochre", "sepia", "taupe", "burgundy",
    "vermilion", "cerulean", "viridian", "tangerine", "sienna",

    # Gemstones / materials with strong color associations
    "emerald", "ruby", "sapphire", "topaz", "amethyst", "garnet", "opal",
    "pearl", "ebony", "jade", "obsidian", "onyx", "quartz",

    # Foods / fruits / spices
    "tomato", "eggplant", "cherry", "berry", "lemon", "kiwi", "grape",
    "mustard", "honey", "mango", "papaya", "watermelon", "raspberry",
    "blackberry", "strawberry", "apricot", "cranberry", "pomegranate",
    "banana", "pumpkin", "carrot", "saffron", "paprika", "cinnamon",
    "chocolate", "mocha", "espresso", "caramel", "vanilla", "almond",
    "pecan", "walnut", "chestnut", "hazelnut", "avocado", "cucumber",
    "spinach", "asparagus", "broccoli", "celery", "ginger", "turmeric",
    "wasabi",

    # Wood / earth
    "mahogany", "cedar", "oak", "teak", "bamboo", "rosewood", "birch",
    "pine", "maple", "clay", "soil", "mud", "sand", "stone", "marble",
    "granite", "slate", "charcoal", "ash", "soot",

    # Nature / sky
    "ocean", "sky", "lava", "snow", "ice", "frost", "fog", "moss", "leaf",
    "grass", "hay", "straw", "wheat", "sunset", "sunrise", "dawn", "dusk",
    "midnight", "twilight", "blush", "flame", "ember", "smoke",
    # "tan" is too short and false-matches "santana", "titanic" etc.
}))


def has_color_hint(name: str) -> bool:
    lower = name.lower()
    return any(h in lower for h in _COLOR_HINT_SUBSTRINGS)


def derive_primary_color(L: float, a: float, b: float) -> str:
    """Classify an OKLab color into one of ~12 primary-color buckets.

    Used as the suffix for palette entries whose name doesn't already convey
    a color. The buckets are intentionally coarse: we want users to know
    roughly what hue they're looking at, not to fight over salmon vs coral.
    """
    chroma = math.sqrt(a * a + b * b)
    if L < 0.15:
        return "Black"
    if L > 0.93 and chroma < 0.04:
        return "White"
    if chroma < 0.025:
        return "Gray"

    hue_deg = math.degrees(math.atan2(b, a)) % 360.0

    # Boundaries calibrated against canonical sRGB primaries:
    #   #ff0000 red       -> ~29°
    #   #ff8000 orange    -> ~54°
    #   #ffff00 yellow    -> ~110°
    #   #00ff00 green     -> ~143°
    #   #00ffff cyan      -> ~195°
    #   #0000ff blue      -> ~264°
    #   #8000ff purple    -> ~308°
    #   #ff00ff magenta   -> ~328°
    if hue_deg >= 350 or hue_deg < 40:
        if L > 0.72 and chroma < 0.15:
            return "Pink"
        if L < 0.42 and chroma < 0.13:
            return "Brown"
        return "Red"
    if hue_deg < 75:
        if L < 0.5 and chroma < 0.13:
            return "Brown"
        return "Orange"
    if hue_deg < 120:
        if L < 0.55:
            return "Olive"
        return "Yellow"
    if hue_deg < 175:
        return "Green"
    if hue_deg < 235:
        if L < 0.6:
            return "Teal"
        return "Cyan"
    if hue_deg < 290:
        return "Blue"
    if hue_deg < 325:
        return "Purple"
    return "Magenta"  # 325-350


def make_display_name(name: str, L: float, a: float, b: float) -> str:
    """Return the user-facing name. Appends a primary-color suffix only when
    the original name has no implicit color cue."""
    if has_color_hint(name):
        return name
    return f"{name} {derive_primary_color(L, a, b)}"


# ----------------------------------------------------------------------------
# Loading + sampling
# ----------------------------------------------------------------------------

class Entry(NamedTuple):
    name: str
    hex: str
    L: float
    a: float
    b: float


def load_entries(path: Path) -> list[Entry]:
    out: list[Entry] = []
    with path.open("r", encoding="utf-8", newline="") as fp:
        reader = csv.DictReader(fp)
        for row in reader:
            name = row["name"].strip()
            hex_str = row["hex"].strip()
            if not name or not hex_str:
                continue
            try:
                L, a, b = hex_to_oklab(hex_str)
            except ValueError:
                continue
            out.append(Entry(name=name, hex=hex_str.lower(), L=L, a=a, b=b))
    return out


def _sq_dist(p: Entry, q: Entry) -> float:
    return (p.L - q.L) ** 2 + (p.a - q.a) ** 2 + (p.b - q.b) ** 2


def farthest_point_sample(pool: list[Entry], k: int, *, seed_hex: str = "#808080") -> list[Entry]:
    """Greedy farthest-point selection of k entries from pool, in OKLab.

    Seed with the pool member closest to a mid-luminance gray, then repeatedly
    pick the candidate whose minimum distance to the already-selected set is
    largest. O(k * n) — fine for n ~ 4k, k = 250.
    """
    if k <= 0 or not pool:
        return []
    if k >= len(pool):
        return list(pool)

    # Pick the seed: closest in OKLab to neutral mid-gray.
    seed_oklab = hex_to_oklab(seed_hex)
    seed_entry = Entry("__seed__", seed_hex, *seed_oklab)
    seed_idx = min(range(len(pool)), key=lambda i: _sq_dist(pool[i], seed_entry))

    chosen: list[Entry] = [pool[seed_idx]]
    # Maintain min-distance to chosen set for every remaining candidate.
    min_d2 = [_sq_dist(p, chosen[0]) for p in pool]
    min_d2[seed_idx] = -1.0  # mark as taken

    for _ in range(1, k):
        # Pick candidate with max min_d2.
        best_i = -1
        best_d2 = -1.0
        for i, d2 in enumerate(min_d2):
            if d2 > best_d2:
                best_d2 = d2
                best_i = i
        if best_i < 0:
            break
        chosen.append(pool[best_i])
        min_d2[best_i] = -1.0
        # Update min_d2 against the newly picked point.
        newp = chosen[-1]
        for i, p in enumerate(pool):
            if min_d2[i] < 0:
                continue
            d2 = _sq_dist(p, newp)
            if d2 < min_d2[i]:
                min_d2[i] = d2

    return chosen


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main() -> None:
    all_entries = load_entries(INPUT_CSV)
    print(f"[palette] loaded {len(all_entries)} named colors")

    # Dedup by hex — the source has multiple names for the same hex; we want
    # one chance per color, otherwise the farthest-point sample can pick
    # near-duplicates.
    by_hex: dict[str, Entry] = {}
    for e in all_entries:
        if not is_evocative(e.name):
            continue
        # First evocative name wins for a given hex.
        by_hex.setdefault(e.hex, e)
    pool = list(by_hex.values())
    print(f"[palette] {len(pool)} evocative + unique-hex candidates")

    chosen = farthest_point_sample(pool, PALETTE_SIZE)
    print(f"[palette] sampled {len(chosen)} entries")

    # Sort the output by OKLab L so palette.csv is easy to skim by hand.
    chosen_sorted = sorted(chosen, key=lambda e: (e.L, e.a, e.b))

    # Compute a coverage stat: median nearest-neighbor distance among picks.
    # Lower = denser palette; we expect ~0.06-0.10 in OKLab for 250 in sRGB.
    if len(chosen_sorted) >= 2:
        nn = []
        for i, p in enumerate(chosen_sorted):
            best = math.inf
            for j, q in enumerate(chosen_sorted):
                if i == j:
                    continue
                d2 = _sq_dist(p, q)
                if d2 < best:
                    best = d2
            nn.append(math.sqrt(best))
        nn.sort()
        med = nn[len(nn) // 2]
        print(f"[palette] median nearest-neighbor OKLab distance: {med:.4f}")
        print(f"[palette]   min: {nn[0]:.4f}  max: {nn[-1]:.4f}")

    suffixed_count = 0
    with OUTPUT_CSV.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.writer(fp)
        writer.writerow(["index", "key_suffix", "name", "display_name", "hex", "L", "a", "b"])
        for i, e in enumerate(chosen_sorted):
            dn = make_display_name(e.name, e.L, e.a, e.b)
            if dn != e.name:
                suffixed_count += 1
            writer.writerow([
                i,
                f"c{i:03d}",
                e.name,
                dn,
                e.hex,
                f"{e.L:.6f}",
                f"{e.a:.6f}",
                f"{e.b:.6f}",
            ])
    print(f"[palette] {suffixed_count} of {len(chosen_sorted)} names "
          f"received a primary-color suffix")
    print(f"[palette] wrote {OUTPUT_CSV}")


if __name__ == "__main__":
    main()
