
CONTAINER c4d_presence
{
	NAME c4d_presence;
	GROUP C4DPRESENCE_MAIN_GROUP
	{
		DEFAULT 1;
		COLUMNS 1;

		GROUP		C4DPRESENCE_GENERAL
		{
			DEFAULT 1;
			BOOL        C4DPRESENCE_GENERALENABLE { ANIM OFF; }
			LONG        C4DPRESENCE_GENERALUPDATE { ANIM OFF; MIN 12; MAX 120; }
			BOOL        C4DPRESENCE_ENABLETIME { ANIM OFF; }
			BOOL        C4DPRESENCE_RESETTIMER { ANIM OFF; }
		}

		GROUP		C4DPRESENCE_ICONS
		{
			DEFAULT 1;
			BOOL		C4DPRESENCE_SHOWVERSION { ANIM OFF; }
			BOOL        C4DPRESENCE_SMALLICONS { ANIM OFF; }
		}

		GROUP		C4DPRESENCE_DETAILS
		{
			DEFAULT 1;
			BOOL		C4DPRESENCE_DFIELD { ANIM OFF; }
			LONG        C4DPRESENCE_DTYPE
			{
				ANIM OFF;
				CYCLE
				{
					C4DPRESENCE_INFODOC;
					C4DPRESENCE_INFOOBJ;
					C4DPRESENCE_INFOPLY;
					C4DPRESENCE_INFOGEN;
					C4DPRESENCE_INFOEFF;
					C4DPRESENCE_INFOLIG;
					C4DPRESENCE_INFOCAM;
					C4DPRESENCE_INFOMAT;
					C4DPRESENCE_INFOTEX;
					C4DPRESENCE_INFOFRM;
				}
			}
			STRING      C4DPRESENCE_DCUSTOM { ANIM OFF; }
			BOOL		C4DPRESENCE_DCYCLE { ANIM OFF; }
		}

		GROUP		C4DPRESENCE_STATE
		{
			DEFAULT 1;
			BOOL		C4DPRESENCE_SFIELD { ANIM OFF; }
			LONG        C4DPRESENCE_STYPE
			{
				ANIM OFF;
				CYCLE
				{
					C4DPRESENCE_INFODOC;
					C4DPRESENCE_INFOOBJ;
					C4DPRESENCE_INFOPLY;
					C4DPRESENCE_INFOGEN;
					C4DPRESENCE_INFOEFF;
					C4DPRESENCE_INFOLIG;
					C4DPRESENCE_INFOCAM;
					C4DPRESENCE_INFOMAT;
					C4DPRESENCE_INFOTEX;
					C4DPRESENCE_INFOFRM;
				}
			}
			STRING      C4DPRESENCE_SCUSTOM { ANIM OFF; }
			BOOL		C4DPRESENCE_SCYCLE { ANIM OFF; }
		}

		GROUP		C4DPRESENCE_RENDERING
		{
			DEFAULT 1;
			BOOL        C4DPRESENCE_RENDERICON { ANIM OFF; }
			BOOL        C4DPRESENCE_GPUSTR { ANIM OFF; }
			BOOL        C4DPRESENCE_RENDERSTATS { ANIM OFF; }
			BOOL        C4DPRESENCE_RENDERFILE { ANIM OFF; }
			BOOL        C4DPRESENCE_RENDERFRAME { ANIM OFF; }
		}

		GROUP       C4DPRESENCE_BUTTONS
		{
			SEPARATOR C4DPRESENCE_B1 { }
			GROUP
			{
				BOOL    C4DPRESENCE_B1ON { ANIM OFF; }
				STRING  C4DPRESENCE_B1LABEL { ANIM OFF; }
				STRING  C4DPRESENCE_B1URL { ANIM OFF; }
			}
			SEPARATOR C4DPRESENCE_B2 { }
			GROUP
			{
				BOOL    C4DPRESENCE_B2ON { ANIM OFF; }
				STRING  C4DPRESENCE_B2LABEL { ANIM OFF; }
				STRING  C4DPRESENCE_B2URL { ANIM OFF; }
			}
		}
		BUTTON C4DPRESENCE_RESETALL { SCALE_H; }
	}
}
